
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';




 
USE MyCupCakes;



DROP TABLE IF EXISTS OrderLines;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS UnfinishedOrders;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Toppings;
DROP TABLE IF EXISTS Bottoms;



CREATE TABLE Users(
userId INT(11) AUTO_INCREMENT,
adminId INT(11) NOT NULL,
username VARCHAR(45) NOT NULL,
pass VARCHAR(45) NOT NULL,
email VARCHAR(45) NOT NULL,
balance DOUBLE(11,2) DEFAULT 100.00,
PRIMARY KEY (UserId)
)
ENGINE = INNODB;

CREATE TABLE Orders(
id INT(11) AUTO_INCREMENT,
userId INT,
orderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id),
KEY userId (userId),
CONSTRAINT Orders_fk_1 FOREIGN KEY(userId) REFERENCES Users (userId)
ON DELETE CASCADE
ON UPDATE CASCADE)
ENGINE = INNODB;


CREATE TABLE Bottoms(
id INT(11) AUTO_INCREMENT,
flavour VARCHAR(45) NOT NULL,
price DOUBLE(11,2) NOT NULL,
PRIMARY KEY (id)
)
ENGINE = INNODB;

CREATE TABLE Toppings( 
id INT(11) AUTO_INCREMENT,
flavour VARCHAR(45) NOT NULL,
price DOUBLE(11,2) NOT NULL,
PRIMARY KEY (id)
)
ENGINE = INNODB;

CREATE TABLE OrderLines(
id INT (11) AUTO_INCREMENT,
amount INT (11) NOT NULL,
price DOUBLE(11,2) NOT NULL,
orderId INT,
bottomId INT,
toppingId INT,
PRIMARY KEY(id),
KEY orderId(orderId), KEY bottomId(bottomId), KEY toppingId(toppingId),
CONSTRAINT orderlines_fk_1 FOREIGN KEY(orderId) REFERENCES Orders(id),
CONSTRAINT orderlines_fk_2 FOREIGN KEY(bottomId) REFERENCES Bottoms(id),
CONSTRAINT orderlines_fk_3 FOREIGN KEY (toppingId) REFERENCES Toppings(id)
ON DELETE CASCADE
ON UPDATE CASCADE)
ENGINE = INNODB;

CREATE TABLE UnfinishedOrders(
id INT (11) AUTO_INCREMENT,
amount INT (11) NOT NULL,
price DOUBLE (11,2) NOT NULL,
bottomId INT,
toppingId INT,
userId INT,
PRIMARY KEY (id),
KEY userId (userId),
KEY bottomId (bottomId),
KEY toppingId (toppingId),
CONSTRAINT unfinishedorders_fk_1 FOREIGN KEY(userId) REFERENCES Users (userId),
CONSTRAINT unfinishedorders_fk_2 FOREIGN KEY(bottomId)REFERENCES Bottoms (id),
CONSTRAINT unfinishedorders_fk_3 FOREIGN KEY(toppingId) REFERENCES Toppings(id)
ON DELETE CASCADE
ON UPDATE CASCADE)
ENGINE = INNODB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;



